# get api_id & api_hash from my.telegram.org
api_id: 25455215
api_hash: '4008aeda4613fe9efe1dd8054803a1e5'
# 13 digit channel id startswith - like -111.......
dump_id: -1002103043775
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: ''
