# get api_id & api_hash from my.telegram.org
api_id: 22737298
api_hash: '0fd8525b71e68920efba198863e4291d'
# 13 digit channel id startswith - like -111.......
dump_id: 'RenderDumps1'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOJgBu0qKfbHV2qx32eZDSxQ_my9tVCj7ikP2l0nvgWu_JqNJkfAq4jAhaCoTKdsDgh2yuH9S5Dllgor8EKFMydqa77OlR1ZhSAsgws4r5j8jxP71XA7um0bEjUki0YzzYNeX2AoyNvWt27Ihu2uw1DjjWPAt95am7QAUfXH1LI-uL68Psr2VgsexqonxDRc3fXIdUBBwSHrZFc-XF8vxV1-gtijfxXElHJ4W5HaPSEDs6i6TKw98AjLAIaEFvdPw3cmLEMdcCUWaXA1V2ErBMa7rQnOwevYOLcyQ-3jKhsQuH03m4EJgvBXRtHi5jWMoDFooLZkLc2VK92yprkQ504hgx6k='
