services:
- type: web
  name: telegram-userbot
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python3 -m ubb"
  envVars:
    - key: api_id
      value: 21597688
    - key: api_hash
      value: "ecf6cdeda16b9be9d26b2233b5c5ae45"
    - key: dump_id
      value: RenderDumps
    - key: string_session
      value: "1BJWap1wBuwovZsPzmccn-MLDV3MbI1gR_tW2-kn7q9KTZErqVEfT_QG2b2QoHinoaFwfSAFw7_aM7XDd_S8I6ZxygQuD5OrrrL46Zo2F8nAidrWW4Djhy2JEttFinc0zfqNHt9KN4-53fJKvB7qHM8nA68uHx5YsARu4HUp6Rf2VAvqN1NgDxSZ-og4DhV9lr7Km-HgEYiL9unW54xSpG9jXHY4F2iSwwC_sWD8OCmz6wIs007zt5nkYRgEoHyvkx4JyCCy3TOneIOmrh5VdJaku9ymO3Gh78yqvKEqQYlD_TrPO5Q5xDsYlY6iWI2P6eu7G6s05kr_oiOx6Aeeixog3IP-UQQM="
